---
# Available `vagrant_box` see: https://app.vagrantup.com/boxes/search
vagrant_box: generic/ubuntu2010

# If you need to run multiple instances of Project VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: projectvm.test
vagrant_machine_name: projectvm
vagrant_ip: 192.168.88.88
vagrant_public_ip: ""

# Minimum required versions.
project_vagrant_version_min: '2.2.0'

# Ensure vagrant plugins are installed.
vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater
