# The absolute path to the root directory of the project. Both Project VM and
# the config file need to be contained within this path.
ENV['PROJECTVM_PROJECT_ROOT'] = "#{__dir__}"

# The relative path from the project root to the config directory where you
# placed your config.yml file.
ENV['PROJECTVM_CONFIG_DIR'] = "box"

# The relative path from the project root to the directory where Project VM is located.
ENV['PROJECTVM_DIR'] = "vendor/oscaner/project-vm"

# Load the real Vagrantfile
load "#{__dir__}/#{ENV['PROJECTVM_DIR']}/Vagrantfile"
