---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - ../default.config.yml

  pre_tasks:
    - import_tasks: tasks/config.yml
      tags: ['always']

    - include_tasks: "tasks/init-{{ ansible_os_family }}.yml"

  roles:
    # Automatically fix timeout issues with NFS on macOS.
    # @see https://github.com/geerlingguy/drupal-vm/issues/2154
    - { role: projectvm.vagrant-nfs-fix, when: vagrant_nfs_fix_enabled }

    # Essential roles.
    - { role: geerlingguy.repo-epel, when: ansible_os_family == 'RedHat' }
    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat', tags: ['webserver', 'php'] }
    - { role: geerlingguy.git }
    - { role: geerlingguy.postfix }

    # Web server.
    - { role: geerlingguy.apache, when: project_webserver == 'apache', tags: ['webserver'] }
    - { role: geerlingguy.nginx, when: project_webserver == 'nginx', tags: ['webserver'] }
    - { role: oscaner.php_webserver, when: project_mode == 'php-webserver', tags: ['webserver', 'php', 'database', 'xdebug'] }
    - { role: oscaner.yii2, when: project_type == 'yii2', tags: ['webserver', 'php', 'yii2'] }

  tasks: []
