---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - ../default.config.yml

  pre_tasks:
    - import_tasks: tasks/config.yml
      tags: ['always']

  roles:
    # Automatically fix timeout issues with NFS on macOS.
    # @see https://github.com/geerlingguy/drupal-vm/issues/2154
    - { role: projectvm.vagrant-nfs-fix, when: vagrant_nfs_fix_enabled }

  tasks: []
