galaxy_info:
  role_name: php_webserver
  author: oscaner
  description: PHP WebServer
  company: ""

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: "license (BSD, MIT)"

  min_ansible_version: 2.8

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic

  galaxy_tags:
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.
    - web
    - php
    - apache
    - nginx

allow_duplicates: true

dependencies:
  - name: geerlingguy.firewall
    version: 2.5.0
    when: firewall_enabled
  - name: geerlingguy.apache
    version: 3.2.0
    when: project_webserver == 'apache'
    tags: ['webserver']
  - name: geerlingguy.apache-php-fpm
    version: 1.1.0
    when: project_webserver == 'apache'
    tags: ['webserver']
  - name: geerlingguy.nginx
    version: 3.1.0
    when: project_webserver == 'nginx'
    tags: ['webserver']
  - name: geerlingguy.php-versions
    version: 5.0.0
    when: php_version != ''
    tags: ['php', 'xdebug', 'database']
  - name: geerlingguy.php
    version: 4.7.0
    tags: ['php']
  - name: geerlingguy.composer
    version: 1.9.0
  - name: geerlingguy.mysql
    when: project_db_backend == 'mysql'
    tags: ['database']
  - name: geerlingguy.php-mysql
    version: 2.1.0
    when: project_db_backend == 'mysql'
    tags: ['php', 'database']
  - name: geerlingguy.postgresql
    version: 3.1.1
    when: project_db_backend == 'pgsql'
    tags: ['database']
  - name: geerlingguy.php-pgsql
    version: 1.0.1
    when: project_db_backend == 'pgsql'
    tags: ['php', 'database']
  - name: geerlingguy.memcached
    version: 2.2.0
    when: '"memcached" in installed_extras'
  - name: geerlingguy.php-memcached
    version: 2.0.2
    when: '"memcached" in installed_extras'
    tags: ['php']
  - name: geerlingguy.php-xdebug
    version: 3.0.0
    when: '"xdebug" in installed_extras'
    tags: ['php', 'xdebug']
